### ISSUE TITLE
Docker gui baseimage

### ISSUE THREAD

**Issue by aptalca** [ruippeixotog/docker-google-musicmanager#6]
Hi,

Great job on this container. I just wanted to let you know of a baseimage that allows running X apps in a web browser (runs a guacamole server on the backend).

The original dev created the baseimage for others to build containers off of and I think this app would be a great fit.

Here's the baseimage: https://hub.docker.com/r/hurricane/dockergui/

I created a few containers using it and it works great.

Here are a few I did: https://hub.docker.com/r/aptalca/docker-jdownloader2/
https://hub.docker.com/r/aptalca/docker-rdp-calibre/
https://hub.docker.com/r/aptalca/docker-digikam/

**Comment by ruippeixotog** [comment]
Hi @aptalca, thanks for your suggestion! I didn't know that image, it seems very useful for running X-only full-fledged applications.

However, in this case it seems rather overkill. The application needs an X server only because of a bad design on its part: this is supposed to be a daemon in most aspects. If you authenticate with username and password via CLI you don't ever need to connect to the GUI through VNC; if you use two-factor auth you need a VNC client, but only for showing a single small square screen to input your credentials. Finally, I am not particularly fond of the `phusion/baseimage` used by `hurricane/dockergui`.

I prefer the image to be the way it is now as it runs with the minimum possible side services possible, as a daemon should be. But I thank you again for the suggestion; despite not using it in this one, I'll surely have that image in account for building future Docker images with X requirements :)

**Comment by aptalca** [comment]
That makes sense. Thanks for the consideration and the comments.
