### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by mindrunner** [ruippeixotog/docker-google-musicmanager#8]
Hi, 
I have problems logging into the google music app.

With mac spoofing enabled, I am getting the following message:
https://productforums.google.com/forum/#!msg/play/Gez5D6BpVjo/U23cM12A62AJ

When Macspoof is disabled, the application sais:
Could not identify your computer.

Any hints? 

Cheers
Lukas

**Comment by ruippeixotog** [comment]
Hi! It seems mac spoofing isn't working well anymore; unfortunately it's difficult for me to test it. I'm using the image with mac spoofing disabled (`-e SPOOF_MAC=false`) and it works well, but it only works if you are not running it in a VM (boot2docker / docker-machine included) and are passing the `--net=host` option on `docker run`. Are you running it that way?

I should probably update the README with these various modes of operation anyway.

**Comment by mindrunner** [comment]
Hi
thanks for the quick answer. My Docker runs on a native Gentoo Linux box. So no VMs involved. using `--net=host` makes me seeing a black screen in my VNC session. No login dialog then :(

Cheers

**Comment by mindrunner** [comment]
any ideas? :(

**Comment by ruippeixotog** [comment]
I'm sorry for taking so long to reply. That's strange... I assume you tried running it without mounting an `/appdata` volume? `/appdata` contains the application state, including the login state - if you logged in at least once, the UI is expected to be just a black screen.

Other than that, I can't provide much more support :( `google-musicmanager` is supposed to run in a full X environment in a simple network setup (i.e. no Docker nor VMs) and has little to no documentation for running it the way we are doing. I just followed the instructions available on the internet for launching the official client in a headless environment (such as the ones in http://superuser.com/questions/429153/using-google-music-manager-in-linux-from-the-command-line/460435).

If you find out what the problem is, please post it here as I'd like to know!

**Comment by mindrunner** [comment]
> Uploaded songs: 48,991 of 50,000

Looks like it was running in the Background all the time doing the right Job. :)

**Comment by ruippeixotog** [comment]
Glad it worked :)
